service: hbccmicroproject

# Not requied by ensures you run the project on the correct version of the framework
frameworkVersion: ">=1.7.0 <2.0.0"

#Chekout Semantic versioning for more details
#semver.org

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.greet
